language: java
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
  packages:
      - g++-6

before_install:
- CC=gcc-6 && CXX=g++-6
- wget petercorke.com/files/MVTB/images-RVC2a.zip
- unzip images-RVC2a
- mkdir lib
- git clone --depth 50 https://github.com/petercorke/toolbox-common-matlab lib/toolbox-common-matlab
- git clone --depth 50 https://github.com/petercorke/spatial-math lib/spatial-math

install: curl -sL https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash

script:
- matlab -sd unit_test -batch "RunAllTests"

after_success:
- bash <(curl -s https://codecov.io/bash)
